FROM rockylinux/rockylinux:9-ubi-init

# Install Puppet 8 repo + agent + HAProxy + tools
RUN rpm -Uvh https://yum.puppet.com/puppet8-release-el-9.noarch.rpm && \
    dnf install -y puppet-agent haproxy procps-ng && \
    dnf clean all

ENV PATH="/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:${PATH}"

# Install required Puppet modules
RUN puppet module install puppetlabs-stdlib --version 9.7.0 && \
    puppet module install puppetlabs-concat --version 9.0.2 && \
    puppet module install puppetlabs-firewall --version 8.1.3

# Copy the Puppet module
COPY modules/profile_haproxy /etc/puppetlabs/code/environments/production/modules/profile_haproxy

# Copy test manifest and hiera config
COPY test/site.pp /etc/puppetlabs/code/environments/production/manifests/site.pp
COPY test/hiera.yaml /etc/puppetlabs/puppet/hiera.yaml
COPY test/data/ /etc/puppetlabs/code/environments/production/data/

# systemd init (from ubi-init base)
CMD ["/sbin/init"]
